#ifndef DEVICE_SETUP
#define DEVICE_SETUP

#define FAN_POWER_PIN 9
#define FAN_POWER_RESOLUTION 8
#define FAN_POWER_SCALE 15
#define FAN_POWER_MIN 30
#define FAN_POWER_MAX 90

#define FAN_POWER_BTN_PULSE_WIDTH 20
#define FAN_POWER_UP_PIN 3
#define FAN_POWER_DOWN_PIN 2

#endif